export const AllPostQuery = `*[_type == "blogs"] | order(_createdAt desc){
    title,
    slug,
    excerpt,
    image{
      asset->{
        url
      }
    },
    content,
    _createdAt,
    featured
}`

export const singleBlog = `*[ _type == "blogs" && slug.current == $slug ][0]{
    title,
    slug,
    excerpt,
    image{
      asset->{
        url
      }
    },
    content,
    _createdAt,
    featured,
    meta_title,
    meta_description,
    meta_tags,
    nofollow,
}`


export const QAllStories = `*[ _type == "customer-stories"] | order(_createdAt desc){
  title,
  slug,
  excerpt,
  image{
    asset->{
      url
    }
  },
  profile_image{
    asset->{
      url
    }
  },
  content,
  _createdAt
}`

export const QsingleStory = `*[ _type == "customer-stories" && slug.current == $slug ][0]{
  title,
  slug,
  excerpt,
  image{
    asset->{
      url
    }
  },
  profile_image{
    asset->{
      url
    }
  },
  content,
  meta_title,
  meta_description,
  meta_tags,
  nofollow,
  _createdAt
}`

export const QHomePage = `*[ _type == "home"]{
  hero_title,
  hero_short_info,
  hero_button_text,
  hero_button_link,
  brands[]{
    asset->{
      url
    }
  },
  who_label,
  who_title,
  who_short_info,
  who_button_text,
  who_button_url,
  who_image{
    asset->{
      url
    }
  },
  domain_title,
  domain_short_info,
  domain_list[]{
    icon{
      asset->{
        url
      }
    },
    title,
    short_info
  },
  domain_middle_icon{
    asset->{
      url
    }
  },
  fs_label,
  fs_title,
  fs_short_info,
  fs_list[]{
    icon{
      asset->{
        url
      }
    },
    title,
    link,
    short_info
  },
  stories[]->{
    title,
    sub_title,
    slug,
    image{
      asset->{
        url
      }
    }
  },
  meta_title,
  meta_description,
  meta_tags
}`